### PR TITLE
[ISSUE LPS-76451] Paragraph field should not have Properties tab

### PR DESCRIPTION
**Pull request by austinskim123**
JIRA issue: https://issues.liferay.com/browse/LPS-76451

### CODE REVIEW

**Comment by mbowerman** [comment]
Hi @austinskim123,

This looks good to me as far as I can tell. Unfortunately I'm also not really familiar with any of these annotations or how to use them. It is very odd that it seems to be necessary to include the DDMFormLayoutRow that references values that aren't in the UI. Hopefully someone further along in the review chain will be more familiar with this stuff and have a more detailed understanding of what it's doing.

**Comment by mbowerman** [comment]
Forwarded to https://github.com/jonathanmccann/com-liferay-dynamic-data-mapping/pull/14

**Comment by austinskim123** [comment]
@mbowerman 
According to the documentation on DDMForms, I think you have to include all the default values in order for the form to render. However, that's why the ones that aren't used are set to be hidden.

**Comment by mbowerman** [comment]
Ah, good find. Thanks!

**Pull request closed without merging**
